### PR TITLE
Switch to `pyproject.toml` and set up CD action

### PR DESCRIPTION
**Pull request by mbercx**

### CODE REVIEW

**Comment by mbercx** [comment]
@sphuber my humble attempt at switching to `pyproject.toml` and setting up a CD action. Seems I still have to change some of the CI though, I'll try and look at that later...

Part of me is wondering if we can't just drop the `qe-tools` dependency in the `aiida-quantumespresso` plugin altogether. ^^

**Comment by unkcpz** [comment]
> Part of me is wondering if we can't just drop the qe-tools dependency in the aiida-quantumespresso plugin altogether. ^^

I think this is not a bad idea.

**Comment by mbercx** [comment]
Just looking for `qe_tools` in the `aiida-quantumespresso` source code, I mainly see usage of the `CONSTANTS` for unit conversions, for which we can use `pint` instead. Besides this, we only really use the input file classes (I'm assuming for calcjob immigrant purposes?).

**Comment by sphuber** [comment]
@mbercx think the PR should be good to go now. Had to change quite a few things to make things working, including updating the pre-commit config. Most problematic is the removal of the old install script that was tested in seperate CI workflows. Not sure what that was achieving and if it is still required. Have removed it for now, because it uses the `setup.py` which is removed here in favor of `pyproject.toml`.

**Comment by mbercx** [comment]
Thanks @sphuber! I had a quick look at the changes, and it all looks good to me. Since I opened the PR, you can self-accept your changes and go ahead with the merge (codecov be damned ^^).

**Review by sphuber — APPROVED** [review]
Partial auto-approve :D

**Pull request merged**
