### PR TITLE
Add missing import path for `extractors`

### PR DESCRIPTION
**Pull request by edan-bainglass**
Imported `extractors` module in main `__init__.py` to support `from qe_tools.extractors import extract` path needed by MaRDA extractors system.

### CODE REVIEW

**Comment by sphuber** [comment]
Why is this necessary? Doing `from qe_tools.extractors import extract` without this works just fine. Not saying we shouldn't add this, don't think there is any harm, but just trying to understand what the problem was that they encountered?

**Comment by edan-bainglass** [comment]
> Why is this necessary? Doing `from qe_tools.extractors import extract` without this works just fine. Not saying we shouldn't add this, don't think there is any harm, but just trying to understand what the problem was that they encountered?

See https://github.com/marda-alliance/metadata_extractors_registry/pull/54/files#r1450396537

For some reason, they were unable to access the `extractors` module. My "fix" appears to have resolved the matter, but it is unclear what caused the issue in the first place. I was not planning do dig further unless an issue arises, as this is somewhat low priority. At least until the final round of testing, which requires some work on their end.

**Review by sphuber — APPROVED** [review]

**Comment by edan-bainglass** [comment]
@sphuber I'm confused. The PR was all checkmarks. But once merged onto `main`, not a single test passed. What gives?

**Comment by sphuber** [comment]
Well, the PR tests ran three weeks ago. But a lot can change in three weeks. Welcome to dependency management 😅 

It looks like the [latest builds](https://github.com/aiidateam/qe-tools/actions/runs/7756900936/job/21155220854) used `pytest==8.0.0` which was [released last week](https://pypi.org/project/pytest/#history). Since this is a major release, it breaks certain plugins. The solution is to pin the major version of `pytest` that we use in the dependencies. Something like `pytest~=7.0`.

**Comment by edan-bainglass** [comment]
Aah, maybe I missed a "this PR is out of sync... update!" notice before merging 😬 I'll pin `pytest` to ~7.0 as you suggest.

**Pull request merged**
